server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource   #当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver    #mysql驱动包
    url: jdbc:mysql://localhost:3306/df?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: 'root'
    password: '123.'
    druid:
      #解决testWhileIdle is true, validationQuery not set问题的方法

      # 默认 true 为 true 时 validationQuery 必须设为非空字符串
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 默认 false 为 true 时 validationQuery 必须设为非空字符串
      # 【建议】配置为true，不影响性能，并且保证安全性。申请连接的时候检测，
      # 如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 默认 true 为 true 时 validationQuery 必须设为非空字符串
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。如果validationQuery为null，
      # testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
      validation-query: select 1

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.example.entities  #所在entity别名包


eureka:
  client:
    register-with-eureka: true   #向注册中心注册自己
    fetch-registry: true   #表示自己就不是注册中心，需要去检索服务
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/    #注册中心地址
  instance:
    instance-id: payment8001 #服务器名称
    prefer-ip-address: true  #ip提示
    lease-expiration-duration-in-seconds: 2 #默认90 移除等待时间
    lease-renewal-interval-in-seconds: 1 #默认30 心跳间隔时间

