server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service  #lb前缀表示采用负载均衡
          predicates:
            - Path=/payment/get/**   #断言,路径相匹配的进行路由
            - Method=GET,POST
#            - After=2020-03-08T10:59:34.102+08:00[Asia/Shanghai]
#            - Before=2020-03-08T10:59:34.102+08:00[Asia/Shanghai]
          filters:
            - AddRequestParamter=X-Request-Id,1024 #过滤器工厂会在匹配的请求头加上一对请求头，X-Request-Id：1024


        - id: payment_routh2
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由

#      routes:
#        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
#          predicates:
#            - Path=/payment/get/**   #断言,路径相匹配的进行路由
#
#        - id: payment_routh2
#          uri: http://localhost:8001
#          predicates:
#            - Path=/payment/lb/**   #断言,路径相匹配的进行路由


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka


